//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Filtros_y_Seguridad.Models
{
    using Filtros_y_Seguridad.Encrypt;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class FiltroSeguridadEntities1 : DbContext
    {
        string databasename = Environment.GetEnvironmentVariable("initial_catalog", EnvironmentVariableTarget.Machine);
        string user = Environment.GetEnvironmentVariable("user_id", EnvironmentVariableTarget.Machine);
        string password = Environment.GetEnvironmentVariable("password", EnvironmentVariableTarget.Machine);
        string p = "FiltroSeguridad";

        public FiltroSeguridadEntities1()
            : base()
        {
            string dbDecrypt = AesEncrypt.DecryptString(databasename, p);
            string userDecrypt = AesEncrypt.DecryptString(user, p);
            string passwordDecrypt = AesEncrypt.DecryptString(password, p);
            //Console.WriteLine(dbDecrypt);

            string conexion = "data source=RENARDROGUE;initial catalog=" + dbDecrypt + ";user id=" + userDecrypt + ";password=" + passwordDecrypt + ";MultipleActiveResultSets=True;App=EntityFramework;";
            this.Database.Connection.ConnectionString = conexion;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuariosInscritos> UsuariosInscritos { get; set; }
    }
}
